name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read    

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o Código do Projeto
        uses: actions/checkout@v4

      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}      

      - name: Construção e Envio da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            rodrigoafonso/fake-shop:latest
            rodrigoafonso/fake-shop:v${{ github.run_number }}
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Obter o Código do Projeto
        uses: actions/checkout@v4

      - name: Autenticar no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
                az account show          

      - name: Configurar o Kubectl
        run: echo "Executando o comando az aks get-credentials --resource-group KUBERNETES --name cluster-rwa-devops-kubernetes --admin"
      - name: Deploy dos manifestos no Kubernetes
        run: echo "Executando o comando kubectl apply"
        
